FROM node:alpine

WORKDIR /usr/src/app

COPY package.json .

RUN npm install --production

ADD . /app

EXPOSE 3000

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
RUN if [ "$NODE_ENV" == "development" ]; then npm install ; fi
